# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.6.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"
description: Example simulated camera for BL01T

entities:
  - type: ADSimDetector.simDetector
    PORT: DET.DET
    P: "{{ _global.get_env('IOC_PREFIX') }}"
    R: ":DET:"

  - type: ADCore.NDPvaPlugin
    PORT: DET.PVA
    PVNAME: "{{ _global.get_env('IOC_PREFIX') }}:PVA:OUTPUT"
    P: "{{ _global.get_env('IOC_PREFIX') }}"
    R: ":PVA:"
    NDARRAY_PORT: DET.DET
