# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.6.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"
description: Example simulated camera for BL01T

entities:
  - type: ADSimDetector.simDetector
    PORT: DET.DET
    P: BL01T-DI-CAM-01
    R: ":DET:"
    WIDTH: 1024
    HEIGHT: 1024

  - type: ADCore.NDPvaPlugin
    PORT: DET.PVA
    PVNAME: BL01T-DI-CAM-01:PVA:OUTPUT
    P: BL01T-DI-CAM-01
    R: ":PVA:"
    NDARRAY_PORT: DET.DET

  - type: ADCore.NDStdArrays
    PORT: DET.ARR
    P: BL01T-DI-CAM-01
    R: ":ARR:"
    NDARRAY_PORT: DET.DET
    TYPE: Int8
    NELEMENTS: 1048576
    FTVL: UCHAR

  # - type: ADCore.NDROI
  #   PORT: DET.ROI
  #   P: BL01T-DI-CAM-01
  #   R: ":ROI:"
  #   NDARRAY_PORT: DET.DET
