services:

  ca-gateway:
    image: pklaus/ca-gateway
    container_name: ca-gateway
    expose:
      - "5064-5065/udp"
      - "5064-5065"
    ports:
      - "5064-5065:5064-5065/udp"
      - "5064-5065:5064-5065"
    restart: always
    networks:
      # the network that's alphabetically first will be the one with the forwarded ports
      a_epics_supervisory:
        ipv4_address: 172.100.255.254
      epics_field:
        ipv4_address: 172.20.255.254
    volumes:
      - ./_conf/access:/access:ro
      - ./_conf/pvlist:/pvlist:ro
    command: -sip 172.100.255.254 -cip 172.20.255.255 -pvlist /pvlist -access /access -log /dev/stdout -debug 1

  bl01t-ea-test-01:
    image: "ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.6.1"
    volumes:
      - ./services/bl01t-ea-test-01/config:/epics/ioc/config
      - opi:/epics/opi/
    networks:
      - epics_field
    tty: true
    stdin_open: true

  bl01t-ea-test-02:
    image: "ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.6.1"
    volumes:
      - ./services/bl01t-ea-test-01/config:/epics/ioc/config
      - opi:/epics/opi/
      # - type: volume
      #   source: opi
      #   target: /epics/opi
      #   volume:
      #     subpath: bl01t-di-test-02
    network_mode: "host"
    tty: true
    stdin_open: true

  bl01t-di-cam-01:
    image: "ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.6.1"
    volumes:
      - ./services/bl01t-di-cam-01/config:/epics/ioc/config
      - opi:/epics/opi/
    tty: true
    stdin_open: true
    expose:
      - "5064-5065/udp"
      - "5064-5065"
    networks:
      - epics_field

  epics-opis:
    image: nginx:1.27
    networks:
      - epics_field
    volumes:
      - opi:/opi

  phoebus:
    image: "ghcr.io/epics-containers/ec-phoebus:latest"
    environment:
      DISPLAY: $DISPLAY
    tty: true
    command: phoebus-product/phoebus.sh -resource /opi/index.bob
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - opi:/opi
    # for X11 to work we need to run as the same UID as the host
    # IMPORTANT: set UIDGID to your host user:group e.g. 1000:1000
    # BUT: always to 0:0 if you are using podman
    user: ${UIDGID}
    # X11 forwarding works without net host - just not at DLS for some reason
    network_mode: "host"

volumes:
  opi:

networks:

  # alphabetically first, so that port forwardings get to this network
  a_epics_supervisory:
    ipam:
      driver: default
      config:
        - subnet: "172.100.0.0/16"

  epics_field:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
