

services:

  epics-opis:
    image: docker.io/nginx:1.27
    networks:
      - channel_access
    volumes:
      - opi:/opi

  phoebus:
    image: ghcr.io/epics-containers/ec-phoebus:latest
    environment:
      DISPLAY: $DISPLAY
    tty: true
    command: phoebus-product/phoebus.sh -resource /opi/index.bob
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - opi:/opi
    # for X11 to work we need to run as the same UID as the host
    # IMPORTANT: set UIDGID to your host user:group e.g. 1000:1000
    # BUT: always to 0:0 if you are using podman
    user: ${UIDGID}
    network_mode: "host"

include:
  - services/bl01t-di-cam-01/compose.yml
  - services/bl01t-ea-test-01/compose.yml

