# the top level compose file represents a set of IOCs that would be deployed
# to a given IOC server
#
# For the example this is a single compose file. However, if you wanted to keep
# all IOCs for a beamline in a single repo but deploy to multiple servers,
# then each server would have its own named compose file

# to deploy IOCs to the local machine clone this repo and use the following:
#  export COMPOSE_PROFILES=deploy
#  docker compose up --detach

include:
  # all profiles
  - services/bl01t-di-cam-01/compose.yml
  - services/bl01t-ea-test-01/compose.yml

  # develop profile only
  - services/phoebus/compose.yml

  # deploy profile only
  - services/gateway/compose.yml
  - services/epics-opis/compose.yml


