services:

  bl01t-di-cam-01:

    extends:
      service: linux_ioc
      file: ../../include/ioc.yml

    image: ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.6.1
    container_name: ${IOC_NAME}

    labels:
      # this should be incremented when changes are made to this file
      # (TODO: can we enforce/automate this?)
      version: 0.1.0

    environment:
      IOCSH_PS1: ${IOC_NAME} >
      IOC_NAME: ${IOC_NAME}
      IOC_PREFIX: $IOC_PREFIX

    volumes:
      - type: volume
        source: opi_auto
        target: /epics/opi
        volume:
          subpath: ${IOC_NAME}

    configs:
      - source: ${IOC_NAME}_config
        target: epics/ioc/config

configs:
  bl01t-di-cam-01_config:
    file: ./config

include:
  - include/networks.yml
  - include/volumes.yml
