# for development and testing it is useful to bring up phoebus instanced to
# interact with the local IOCs PVs.

services:
  phoebus:
    image: ghcr.io/epics-containers/ec-phoebus:latest
    environment:
      DISPLAY: $DISPLAY
    tty: true
    command: phoebus-product/phoebus.sh -resource /opi/index.bob
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - opi:/opi
    # for X11 to work we need to run as the same UID as the host
    # IMPORTANT: set UIDGID to your host user:group e.g. 1000:1000
    # BUT: always to 0:0 if you are using podman
    user: ${UIDGID}

    # network host with a gateway for CA is the most reliable way to
    # get X11 forwarding to work - even with ssh->container. But I need
    # to work out how to configure ca-gateway with podman
    # network_mode: host
    networks:
      - channel_access

    profiles:
      - develop
      - phoebus
