# A basic init service that sets up volumes for the IOCs described in
# this repo.

services:
  init_iocs:
    image: docker.io/busybox

    command: |
      sh /repo/include/init.sh

    volumes:
      # mount the runtime opi folder
      - ../services/opi:/opi/
      # mount the repo to copy hand coded opis into runtime opi
      - ..:/repo
